project_id = "cslpnhccmcoxzmxwlaqy"

[functions.compile-font]
verify_jwt = false

[functions.seed-demo-users]
verify_jwt = false

[functions.fast-login-profile]
verify_jwt = false

[functions.auth-proxy]
verify_jwt = false

[functions.admin-query]
verify_jwt = false

[functions.public-courses]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false
