import { useState, useEffect } from 'react';
import { Type, Download, Loader2, Keyboard } from 'lucide-react';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import { FontMetadata } from './FontMetadataConfig';
import { HandwritingRenderer } from './HandwritingRenderer';

interface LiveTypeTesterProps {
  metadata: FontMetadata;
  onExportFont: () => void;
  isExporting: boolean;
}

const SYSTEM_FONTS = [
  { value: 'default', label: 'System Default' },
  { value: 'serif', label: 'Serif' },
  { value: 'sans-serif', label: 'Sans-Serif' },
  { value: 'monospace', label: 'Monospace' },
  { value: 'cursive', label: 'Cursive' },
];

export function LiveTypeTester({ metadata, onExportFont, isExporting }: LiveTypeTesterProps) {
  const [text, setText] = useState('The quick brown fox jumps over the lazy dog.');
  const [selectedFont, setSelectedFont] = useState('generated');
  const [fontSize, setFontSize] = useState(32);
  const [fontUrl, setFontUrl] = useState<string | null>(null);
  const [characterCount, setCharacterCount] = useState(0);
  const [isLoadingFont, setIsLoadingFont] = useState(false);

  useEffect(() => {
    if (selectedFont === 'generated') {
      loadGeneratedFont();
    } else {
      setFontUrl(null);
    }
  }, [selectedFont]);

  useEffect(() => {
    // Count recorded characters
    const fetchCharCount = async () => {
      const { count } = await supabase
        .from('font_library')
        .select('*', { count: 'exact', head: true });
      setCharacterCount(count || 0);
    };
    fetchCharCount();
  }, []);

  const loadGeneratedFont = async () => {
    setIsLoadingFont(true);
    try {
      // In production, this would call the Python API to generate the font
      // For now, we'll show a preview using the stored vector data
      // The font URL would be generated by the backend
      
      // Simulate font loading
      await new Promise(resolve => setTimeout(resolve, 500));
      
      // This would be replaced with actual font URL from the API
      setFontUrl(null);
      
    } catch (error) {
      console.error('Error loading generated font:', error);
    } finally {
      setIsLoadingFont(false);
    }
  };

  const getFontFamily = () => {
    if (selectedFont === 'generated' && fontUrl) {
      return `'MyGeneratedFont', cursive`;
    }
    if (selectedFont === 'default') {
      return 'inherit';
    }
    return selectedFont;
  };

  const handleExport = () => {
    if (characterCount < 26) {
      toast({
        title: "Incomplete Character Set",
        description: `You've recorded ${characterCount} characters. Record at least A-Z (26) to export a basic font.`,
        variant: "destructive",
      });
      return;
    }
    onExportFont();
  };

  return (
    <div className="panel-glass p-4 space-y-4">
      <div className="flex items-center justify-between pb-3 border-b border-border/50">
        <div className="flex items-center gap-2">
          <Keyboard className="w-4 h-4 text-accent" />
          <h3 className="text-sm font-semibold uppercase tracking-wider">Live Type Tester</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">{characterCount} chars recorded</span>
        </div>
      </div>

      {/* Font Selection */}
      <div className="flex items-center gap-3">
        <Select value={selectedFont} onValueChange={setSelectedFont}>
          <SelectTrigger className="w-48 bg-secondary/50 border-border/50">
            <SelectValue placeholder="Select font" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="generated" className="flex items-center gap-2">
              <span className="text-accent">✨</span> My Generated Font
            </SelectItem>
            {SYSTEM_FONTS.map(font => (
              <SelectItem key={font.value} value={font.value}>
                {font.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <div className="flex items-center gap-2 flex-1">
          <Type className="w-4 h-4 text-muted-foreground" />
          <Slider
            value={[fontSize]}
            onValueChange={([value]) => setFontSize(value)}
            min={16}
            max={72}
            step={2}
            className="w-32"
          />
          <span className="font-mono text-sm text-muted-foreground w-10">{fontSize}px</span>
        </div>

        <Button
          onClick={handleExport}
          disabled={isExporting || characterCount < 26}
          variant="outline"
          className="border-accent/50 text-accent hover:bg-accent/10"
        >
          {isExporting ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Download className="w-4 h-4 mr-2" />
              Export OTF
            </>
          )}
        </Button>
      </div>

      {/* Font Preview Area */}
      <div className="relative min-h-[200px] bg-secondary/30 border border-border/50 rounded-lg p-4">
        {isLoadingFont && selectedFont === 'generated' && (
          <div className="absolute inset-0 bg-background/80 flex items-center justify-center rounded-lg z-10">
            <Loader2 className="w-6 h-6 animate-spin text-primary" />
          </div>
        )}

        {selectedFont === 'generated' ? (
          /* Render using handwriting vectors */
          <HandwritingRenderer
            text={text}
            fontSize={fontSize}
            lineHeight={metadata.lineHeight}
            letterSpacing={metadata.globalKerning}
          />
        ) : (
          /* Render using system font */
          <div
            className="whitespace-pre-wrap break-words"
            style={{
              fontFamily: getFontFamily(),
              fontSize: `${fontSize}px`,
              lineHeight: `${metadata.lineHeight}%`,
              letterSpacing: `${metadata.globalKerning / 100}em`,
            }}
          >
            {text}
          </div>
        )}
      </div>

      {/* Text Input */}
      <Textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Type here to test your font..."
        className="min-h-[80px] bg-secondary/30 border-border/50 resize-none text-sm"
      />

      {/* Sample Texts */}
      <div className="space-y-2">
        <div className="text-xs text-muted-foreground uppercase tracking-wider">Quick Samples</div>
        <div className="flex flex-wrap gap-2">
          {[
            'The quick brown fox jumps over the lazy dog.',
            'Pack my box with five dozen liquor jugs.',
            'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
            'abcdefghijklmnopqrstuvwxyz',
            '0123456789',
          ].map((sample, i) => (
            <button
              key={i}
              onClick={() => setText(sample)}
              className="px-3 py-1.5 bg-secondary/50 hover:bg-secondary rounded-lg text-xs text-muted-foreground hover:text-foreground transition-colors"
            >
              {sample.length > 30 ? sample.slice(0, 30) + '...' : sample}
            </button>
          ))}
        </div>
      </div>

      {/* Export Requirements */}
      <div className="pt-3 border-t border-border/50">
        <div className="flex items-center justify-between text-xs">
          <span className="text-muted-foreground">Export Requirements</span>
          <div className="flex items-center gap-4">
            <span className={characterCount >= 26 ? "text-success" : "text-destructive"}>
              A-Z: {Math.min(characterCount, 26)}/26
            </span>
            <span className={characterCount >= 52 ? "text-success" : "text-muted-foreground"}>
              a-z: {Math.max(0, Math.min(characterCount - 26, 26))}/26
            </span>
            <span className={characterCount >= 62 ? "text-success" : "text-muted-foreground"}>
              0-9: {Math.max(0, Math.min(characterCount - 52, 10))}/10
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
